-- MySQL Script generated by MySQL Workbench
-- lun 08 dic 2025 18:39:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dim_tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dim_tiempo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dim_tiempo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `year_UNIQUE` (`year` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dim_lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dim_lugar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dim_lugar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_calidad_vida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_calidad_vida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_calidad_vida` (
  `id_tiempo` INT NOT NULL,
  `id_lugar` INT NOT NULL,
  `indice_gini` DOUBLE NULL,
  `poblacion_total` INT NULL,
  `pib_per_capita` DOUBLE NULL,
  `pib_unidad_consumo` DOUBLE NULL,
  `desbalance_s80_s20` DOUBLE NULL,
  `indice_precios_consumo` DOUBLE NULL,
  `variacion_anual_ipc` DOUBLE NULL,
  `indice_calidad_vida` DOUBLE NULL,
  `nivel_contaminacion` DOUBLE NULL,
  PRIMARY KEY (`id_tiempo`, `id_lugar`),
  INDEX `id_lugar` (`id_lugar` ASC) VISIBLE,
  INDEX `id_tiempo_INDEX` (`id_tiempo` ASC) VISIBLE,
  CONSTRAINT `fk_registro_calidad_vida_id_tiempo`
    FOREIGN KEY (`id_tiempo`)
    REFERENCES `mydb`.`dim_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_calidad_vida_id_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`dim_lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
