-- MySQL Script generated by MySQL Workbench
-- Fri Nov 28 10:36:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dim_tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dim_tiempo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dim_tiempo` (
  `id_tiempo` INT NOT NULL AUTO_INCREMENT,
  `anyo` INT NULL,
  PRIMARY KEY (`id_tiempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dim_ccaa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dim_ccaa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dim_ccaa` (
  `id_ca` INT NOT NULL AUTO_INCREMENT,
  `nombre_ca` VARCHAR(50) NULL,
  PRIMARY KEY (`id_ca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fact_calidad_vida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fact_calidad_vida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fact_calidad_vida` (
  `sueldo_medio` DOUBLE NULL,
  `pib` DOUBLE NULL,
  `poblacion_total` INT NULL,
  `edad_media` DOUBLE NULL,
  `tasa_paro` DOUBLE NULL,
  `esperanza_vida` DOUBLE NULL,
  `cantidad_turistas` INT NULL,
  `indice_gini` DOUBLE NULL,
  `nivel_contaminacion_ica` DOUBLE NULL,
  `dim_tiempo_id_tiempo` INT NOT NULL,
  `dim_ccaa_id_ca` INT NOT NULL,
  PRIMARY KEY (`dim_tiempo_id_tiempo`, `dim_ccaa_id_ca`),
  INDEX `fk_fact_calidad_vida_dim_ccaa1_idx` (`dim_ccaa_id_ca` ASC) VISIBLE,
  CONSTRAINT `fk_fact_calidad_vida_dim_tiempo`
    FOREIGN KEY (`dim_tiempo_id_tiempo`)
    REFERENCES `mydb`.`dim_tiempo` (`id_tiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fact_calidad_vida_dim_ccaa1`
    FOREIGN KEY (`dim_ccaa_id_ca`)
    REFERENCES `mydb`.`dim_ccaa` (`id_ca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
